[build]
  command = "npm run build"
  publish = ".output/public"


[build.environment]
  NODE_VERSION = "24"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--legacy-peer-deps"

# Enable caching
[build.processing]
  skip_processing = false

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
